apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
    {{ include "weather-api.fullname" . }}
  labels:
    {{- include "weather-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "weather-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "weather-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}